### ISSUE TITLE
zstd mem leak on re-use

### ISSUE THREAD

**Issue by pforemski** [klauspost/compress#370] opened 2021-05-05 09:09 UTC
Hi,

I'm using compress 1.12.2 for zstd compression, in the following manner. I'm writing many files every minute, for each file I begin with:

```
me.zstd, err = zstd.NewWriter(nil, zstd.WithEncoderCRC(false))
```

And then, for each file, I call the following function ~100k times:

```
// me.ztmp is []byte, nil on first call
func (me *Writer) compressZstd(buf []byte) []byte {
	me.ztmp = me.zstd.EncodeAll(buf, me.ztmp[:0])
	return me.ztmp
}
```

After each call, I append the result to file, and repeat the call, hopefully re-using memory. Each file is written in a single goroutine.

I also tried the streaming API, with worse results.

The problem is, I'm seeing a massive mem leak after a few hours. For instance, pprof says:

```
pjf@pjf:~$ go tool pprof http://localhost:6060/debug/pprof/heap
Fetching profile over HTTP from http://localhost:6060/debug/pprof/heap
Saved profile in --REDACTED--
File: --REDACTED--
Type: inuse_space
Time: May 5, 2021 at 10:59am (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 35929.63MB, 86.13% of 41717.42MB total
Dropped 79 nodes (cum <= 208.59MB)
Showing top 10 nodes out of 63
      flat  flat%   sum%        cum   cum%
12650.50MB 30.32% 30.32% 12650.50MB 30.32%  github.com/klauspost/compress/zstd.(*frameDec).initAsync
11398.74MB 27.32% 57.65% 11398.74MB 27.32%  github.com/klauspost/compress/zstd.encoderOptions.encoder
 2290.30MB  5.49% 63.14%  2290.30MB  5.49%  github.com/klauspost/compress/zstd.(*blockEnc).init
 2130.14MB  5.11% 68.24%  2130.14MB  5.11%  github.com/klauspost/compress/zstd.(*blockDec).reset
 1946.44MB  4.67% 72.91%  3683.27MB  8.83%  --REDACTED--
 1828.08MB  4.38% 77.29%  1906.25MB  4.57%  --REDACTED--
 1092.23MB  2.62% 79.91%  1795.58MB  4.30%  github.com/klauspost/compress/zstd.(*blockDec).decodeCompressed
 1060.72MB  2.54% 82.45%  1060.72MB  2.54%  --REDACTED--
     800MB  1.92% 84.37%      800MB  1.92%  github.com/klauspost/compress/zstd.(*fastBase).ensureHist
  732.48MB  1.76% 86.13%  1542.70MB  3.70%  --REDACTED--
(pprof) list initAsync
Total: 40.74GB
ROUTINE ======================== github.com/klauspost/compress/zstd.(*frameDec).initAsync in /home/pjf/go/pkg/mod/github.com/klauspost/compress@v1.12.2/zstd/framedec.go
   12.35GB    12.35GB (flat, cum) 30.32% of Total
         .          .    333:	// re-alloc if more than one extra block size.
         .          .    334:	if d.o.lowMem && cap(d.history.b) > d.history.maxSize+maxBlockSize {
         .          .    335:		d.history.b = make([]byte, 0, d.history.maxSize)
         .          .    336:	}
         .          .    337:	if cap(d.history.b) < d.history.maxSize {
   12.35GB    12.35GB    338:		d.history.b = make([]byte, 0, d.history.maxSize)
         .          .    339:	}
         .          .    340:	if cap(d.decoding) < d.o.concurrent {
  512.05kB   512.05kB    341:		d.decoding = make(chan *blockDec, d.o.concurrent)
         .          .    342:	}
         .          .    343:	if debug {
         .          .    344:		h := d.history
         .          .    345:		printf("history init. len: %d, cap: %d", len(h.b), cap(h.b))
         .          .    346:	}
(pprof) list encoderOptions.encoder
Total: 40.74GB
ROUTINE ======================== github.com/klauspost/compress/zstd.encoderOptions.encoder in /home/pjf/go/pkg/mod/github.com/klauspost/compress@v1.12.2/zstd/encoder_options.go
   11.13GB    11.13GB (flat, cum) 27.32% of Total
         .          .     52:
         .          .     53:	case SpeedDefault:
         .          .     54:		if o.dict != nil {
         .          .     55:			return &doubleFastEncoderDict{fastEncoderDict: fastEncoderDict{fastEncoder: fastEncoder{fastBase: fastBase{maxMatchOff: int32(o.windowSize), lowMem: o.lowMem}}}}
         .          .     56:		}
   11.13GB    11.13GB     57:		return &doubleFastEncoder{fastEncoder: fastEncoder{fastBase: fastBase{maxMatchOff: int32(o.windowSize), lowMem: o.lowMem}}}
         .          .     58:	case SpeedBetterCompression:
         .          .     59:		if o.dict != nil {
         .          .     60:			return &betterFastEncoderDict{betterFastEncoder: betterFastEncoder{fastBase: fastBase{maxMatchOff: int32(o.windowSize), lowMem: o.lowMem}}}
         .          .     61:		}
         .          .     62:		return &betterFastEncoder{fastBase: fastBase{maxMatchOff: int32(o.windowSize), lowMem: o.lowMem}}
(pprof) 
```

Any ideas before I start digging?

**Comment by klauspost** [comment] 2021-05-05 10:33
@pforemski The problem is not in the code you are supplying, except that you are not really reusing, but creating a new encoder per file.

Since you are just using `EncodeAll` you can use a single instance for *all* files. This is safe and allows for concurrent compression.

Something like:

```
var zstdEnc *zstd.Encoder

func init() {
  zstdEnc, _ = zstd.NewWriter(nil, zstd.WithEncoderCRC(false))
}

// me.ztmp is []byte, nil on first call
func (me *Writer) compressZstd(buf []byte) []byte {
	me.ztmp =  zstdEnc.EncodeAll(buf, me.ztmp[:0])
	return me.ztmp
}
```

**Comment by pforemski** [comment] 2021-05-05 12:10
Ah, I *was* re-using the encoder, but added this "re-init" as a temporary workaround to let Golang's GC collect and free old (and big) objects. I was seeing the same problem without the NewWriter call for each new file.

I know I could use single instance for all files, but I don't understand why I'm seeing 25GB of RAM usage if I have an encoder per each file. I understand an encoder can grow, but I don't understand why so much.

Anyway, thanks for feedback and your great library. I'm just trying to make sure if I really need to dig deeper.

**Comment by klauspost** [comment] 2021-05-05 12:22
@pforemski If you can supply a complete reproducer I would be happy to investigate, but for now I would only be guessing.

**Comment by klauspost** [comment] 2021-05-10 08:55
Closing for now. Feel free to open another issue if you get a clean reproducer.

**Closed by klauspost** 2021-05-10 08:55 UTC
